### ISSUE TITLE
🐛 Bug Report: Hotel Booking page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#225] opened 2022-09-29 14:06 UTC
### 👟 Reproduction steps

Other hotel shows another hotel booking 

### 👍 Expected behavior

Should be  shows particular hotel data 

### 👎 Actual Behavior

Uploading WhatsApp Video 2022-09-29 at 7.14.30 PM.mp4…

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment] 2022-09-30 20:25
There's something wrong here

**Comment by rvndsngwn** [comment] 2022-09-30 20:51
https://github.com/Rehachoudhary0/hotel_testing/issues/221

Duplicate of #221

**Closed by rvndsngwn** 2022-09-30 20:51 UTC
Labels: bug, duplicate, invalid, app, front-end (UI/UX), High priority
